### ISSUE TITLE
Why do you use UPnP nat traversal instead of ICE (STUN, TURN, UDP hole punching)?

### ISSUE THREAD

**Issue by Hixon10** [perlin-network/noise#113]
Hello.

I am looking for solution for 2P2 file sharing. Your library looks good, but it seems, that there is a problem with nat traversal. You use UPnP nat traversal. But, what if client router does not support it? 

I would be happy to know, why you decide to use UPnP nat traversal instead of ICE? Can you explain, please?

**Comment by iwasaki-kenta** [comment]
We have NAT-PMP and UPnP as both viable options (NAT-PMP will be released in the upcoming v1.1 released of Noise).

Admittedly, we want to refrain from including methods that require rendezvous servers for discovering new peers (for obvious reasons).

Since it seems like it may be turning into a popular option however, we can include a fallback option to NAT-PMP and UPnP the option to dial an ICE server for NAT traversal 😄.

**Comment by Hixon10** [comment]
Thanks for your response!
